builds:
  - id: api
    dir: ./cmd/api
    binary: api
    goos:
      - linux
    goarch:
      - amd64

  - id: vertexctl
    dir: ./cmd/vertexctl
    binary: vertexctl
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: vertexctl
    package_name: vertexctl
    file_name_template: "edged_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Packetframe
    homepage: https://github.com/packetframe/api
    maintainer: Nate Sales <nate@packetframe.com>
    description: Packetframe vertex edge firewall controller
    license: GNU GPL-3.0
    section: utils
    priority: extra
    formats:
      - deb

dockers:
  - ids: [ "api" ]
    image_templates: [ "ghcr.io/packetframe/vertex:{{ .Version }}" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0-only
