builds:
  - id: api
    dir: ./cmd/api
    binary: api
    goos:
      - linux
    goarch:
      - amd64

  - id: vertexctl
    dir: ./cmd/vertexctl
    binary: vertexctl
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - ids: [ "api", "vertexctl" ]
    image_templates: [ "ghcr.io/packetframe/vertex:{{ .Version }}" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0-only
