name: Test

on:
  push:
    branches:
      - main
    paths:
      - "*.go"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Run test
        run: go test -v -race ./...
